---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: JohnAtl_Bluefin
# description will be included in the image's metadata
description: This is my OS image based on John's specifications.
---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin
# description will be included in the image's metadata
description: This is a custom image that includes 1Password to work with Firefox and Chromium. It also includes PowerShell via .NET SDK, Astra Monitor, Tiling Shell, and amdgpu_top for AMD GPU monitoring.

# the base image to build on top of (FROM) and the version tag to use
base-image: bluefin-dx-nvidia-open
image-version: gts

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      # - https://packages.microsoft.com/fedora/42/prod/config.repo
      # - https://packages.microsoft.com/yumrepos/edge/config.repo
    optfix:
      # - brave.com
      # - microsoft
    keys:
      # - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      # - https://packages.microsoft.com/keys/microsoft-2025.asc
    install:
      # - brave-browser
      # - microsoft-edge-stable
      # - microsoft-edge-beta
      # - packages-microsoft-prod
      - chromium
      - dotnet-sdk-9.0
      # - nethogs # network traffic monitor for Astra Monitor
      # - https://github.com/Umio-Yasuno/amdgpu_top/releases/download/v0.10.5/amdgpu_top-0.10.5-1.x86_64.rpm # GPU monitoring tool for Astra Monitor
      - https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.rpm
      - firefox
      - firefox-langpacks

  # https://blue-build.org/reference/modules/bling/
  - type: bling
    install:
      - 1password

  # Install PowerShell via .NET SDK
  - type: script
    snippets:
      - "dotnet tool install --global PowerShell"
      - "dotnet tool update --global PowerShell"

  # Install Astra Monitor and Tiling Shell GNOME extensions (for AMD GPU monitoring and window tiling)
  # - type: gnome-extensions
  #   install:
  #     - Astra Monitor
  #     - Tiling Shell

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
