---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: JohnAtl_Bluefin
# description will be included in the image's metadata
description: This is my OS image based on John's specifications.
base-image: ghcr.io/ublue-os/bluefin-dx-nvidia-open
image-version: gts
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    # repos:
    # - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    # - https://packages.microsoft.com/fedora/42/prod/config.repo
    # - https://packages.microsoft.com/yumrepos/edge/config.repo
    # optfix:
    # - brave.com
    # - microsoft
    # keys:
    # - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    # - https://packages.microsoft.com/keys/microsoft-2025.asc
    install:
      # - brave-browser
      # - microsoft-edge-stable
      # - microsoft-edge-beta
      # - packages-microsoft-prod
      - chromium
      - dotnet-sdk-9.0
      - kernel-devel
      - https://raw.githubusercontent.com/zfsonlinux/zfsonlinux.github.com/refs/heads/master/fedora/zfs-release-2-8.fc42.noarch.rpm
      # - nethogs # network traffic monitor for Astra Monitor
      # - https://github.com/Umio-Yasuno/amdgpu_top/releases/download/v0.10.5/amdgpu_top-0.10.5-1.x86_64.rpm # GPU monitoring tool for Astra Monitor
      - https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.rpm
      - firefox
      - firefox-langpacks

  # https://blue-build.org/reference/modules/bling/
  - type: bling
    install:
      - 1password

  - type: rpm-ostree
    install:
      - kernel-devel-6.16.7

  # Install PowerShell via .NET SDK
  - type: script
    snippets:
      - "dotnet tool install --global PowerShell"
      - "dotnet tool update --global PowerShell"

  - type: rpm-ostree
    install:
      - zfs

  # Install Astra Monitor and Tiling Shell GNOME extensions (for AMD GPU monitoring and window tiling)
  # - type: gnome-extensions
  #   install:
  #     - Astra Monitor
  #     - Tiling Shell
  - type: script
    snippets:
      - "modprobe zfs"
      - "echo zfs > /etc/modules-load.d/zfs.conf"
      - "echo 'zfs' > /etc/dnf/protected.d/zfs.conf"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
